### ISSUE TITLE
Basic functionality in script.js

### ISSUE THREAD

**Issue by Allen-B1** [simgames/ttt#2]
Make script.js

`id`s:
`r1c1` is row 1 column 1
`r1c2` is row 1 column 2
etc.

**Comment by Allen-B1** [comment]
hi

**Comment by johnnyr26** [comment]
I want to do the js file, I just need you to make an x and an o thing in style.css

**Comment by Allen-B1** [comment]
OK, I'll unassign myself

**Comment by Allen-B1** [comment]
But we already made `script.js`

**Comment by Allen-B1** [comment]
I added a milestone

**Comment by Allen-B1** [comment]
Computer turn doesn't work

**Comment by johnnyr26** [comment]
Now it does

**Comment by johnnyr26** [comment]
There was an error for the checkWinner() so I'm fixing that now

**Comment by Allen-B1** [comment]
Ok I think it's done is it?

**Comment by Allen-B1** [comment]
Ok if it's not then reopen
